### ISSUE TITLE
Feature: Add support for customizable baud rate

### ISSUE THREAD

**Issue by noob247365** [LucidVR/opengloves-driver#119]
I've been trying to get my own simple "glove" working with an ELEGOO UNO R3, and noticed that when attempting to communicate via the current 115200 baud rate, it will consistently send out `'\0'`. This happens even with the serial monitor included with the Arduino IDE. However when I lower it to 9600, both the serial monitor and your driver appear to read the values correctly. Perhaps there's a higher value I could've used, but I know for a fact 9600 works fine.

Would it be possible to update "communication_serial" section of the vrsettings file to include a "baud_rate" field?

**Comment by danwillm** [comment]
115200 is the current set baud rate for the driver, but I'll work on adding a setting which can change that :+1:
