### ISSUE TITLE
Add more scenarios to troubleshooting FAQ in wiki section

### ISSUE THREAD

**Issue by lucas-vrtech** [LucidVR/opengloves-driver#135]
A great first task for those who have already experimented with the driver.
It would be nice to add some more troubleshooting scenarios to the wiki page https://github.com/LucidVR/opengloves-driver/wiki/Troubleshooting

**Comment by minystreem** [comment]
what scenarios are you thinking of, sry I just saw this

**Comment by minystreem** [comment]
Done!

**Comment by minystreem** [comment]
You can close this issue
