### ISSUE TITLE
Discord Invite Expired or Invalid

### ISSUE THREAD

**Issue by curieos** [LucidVR/opengloves-driver#170]
I tried clicking on the discord invite link but it seems it's expired or something. Did something happen?

**Comment by LittleNyanCat** [comment]
That link on the footer is a really recent addition and the server is nice and well, so maybe Dan tripped up and forgot to make it never expire or something

**Comment by danwillm** [comment]
oof, looks like our vanity url expired.

Use this, I'll update the readme for the driver + ui to this as well: https://discord.gg/favJqS2k4X

Should be a permanent link now. Thanks for the report!
