### ISSUE TITLE
Bluetooth Serial HCI Bus Driver

### ISSUE THREAD

**Issue by hrkrx** [LucidVR/opengloves-driver#55]
Shouldn't it be relatively easy to adopt the generic driver by microsoft (https://docs.microsoft.com/en-us/samples/microsoft/windows-driver-samples/bluetooth-serial-hci-bus-driver/)?

**Comment by danwillm** [comment]
We are looking at adding bluetooth support, there's some nice windows bluetooth apis which we are looking at using but nothing final yet...
https://docs.microsoft.com/en-us/windows/win32/api/bluetoothapis/

Though, we are more than happy to accept pull requests if you want to go ahead and implement something like this yourself.
