### ISSUE TITLE
Transition Checksum

### ISSUE THREAD

**Issue by gaming-se** [LucidVR/opengloves-driver#61]
Hi,
Serial transition might have errors at some point it might cause unexpected behavior so adding a checksum for each packet might be useful.

Kind Regards

**Comment by danwillm** [comment]
Something like this could help, but we haven't really seen a need for use of a checksum. If we find the packet to be invalid while parsing it, we can simply drop it and wait for the next one to come in.

From my testing, I've never really run into any issues with this approach, and also haven't really errors while transmitting through serial.

I'm going to close this issue for now, but if you'd like to open a pr with this included, you are more than welcome to open this issue back up and I would be more than happy to accept it.
