### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by fharni** [LucidVR/opengloves-driver#65]
I try to build this driver and got the following error messages:
`[build] E:\Quellcode\opengloves-driver\src\DeviceDriver\KnuckleDriver.cpp:11:1: error: a storage class can only be specified for objects and functions
[build]  static const enum ComponentIndex : int {
[build]  ^~~~~~
[build] E:\Quellcode\opengloves-driver\src\DeviceDriver\LucidGloveDriver.cpp:15:1: error: a storage class can only be specified for objects and functions
[build]  static const enum ComponentIndex : int {
[build]  ^~~~~~`
I build in Visual Studio Code with MinGw under Windows 10.

**Comment by danwillm** [comment]
We use Microsoft Visual C++ compiler for building the project. Looking at the code, it looks like there was a wrong declaration with an enum - could you try using the `fix-gcc` branch I've just pushed, and let me know if that works for you?

**Comment by fharni** [comment]
Great work. Now it is compiling successful.

**Comment by danwillm** [comment]
Great.

Just to double check, was this using the new branch or using MS Visual C++ compiler?

**Comment by fharni** [comment]
The new branch works with the MinGw compiler.

**Comment by danwillm** [comment]
Cool, thanks for confirming. I'll merge these changes in.
